services:
  server:
    build: ./server
    ports: ["8080:8080"]
    environment:
      - PORT=8080
      - DB_DRIVER=sqlite
      - DB_FILE=/data/helpdesk.db
      - CLIENT_ORIGIN=http://localhost:5173
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=changeme
      - JWT_SECRET=devsecret
      - TELEGRAM_BOT_TOKEN=
      - TELEGRAM_NOTIFY_CHAT_ID=
      - TELEGRAM_WEBHOOK_URL=
    volumes:
      - server_data:/data
      - ./server/uploads:/app/uploads
  client:
    build: ./client
    ports: ["5173:5173"]
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - server
volumes:
  server_data:
